### ISSUE TITLE
Menu items named "undefined"

### ISSUE THREAD

**Issue by PupaRebbe** [vnh1968/ERH#1]
![image](https://user-images.githubusercontent.com/13204991/74004763-c4686080-4944-11ea-976f-aea47b2a001d.png)

**Comment by vnh1968** [comment]
The problem is that there is no support file for the en-UK language. Try to rename the file ERH_0.1.2-en_US.xml by changing "US" to "UK" or make a copy of ERH_0.1.2-en_US.xml and rename it.  

You can correct the translation of this file and send it to my address for placement (mailto:vnh1968@gmail.com).

I will be glad to answer your questions. 
V. Horobchenko
